- name: "Mon Playbook"
  hosts: all
  become: yes
  tasks:
  - name: "debug sans delegation"
    debug:
      var: var2
  - name: "debug avec delegation"
    debug:
      var: var2
    delegate_to: node6
    
      

