- name: "Mon Playbook"
  hosts: all
  become: yes
  tasks:
  - name: "creation du fichier avec delegation"
    file:
      state: touch
      path: /tmp/choky.txt
    delegate_to: node6
# wuth run_once
    run_once: yes      

