- name: "Installation de la clef ssh"
  connection: local
  hosts: 127.0.0.1
  roles:
  - ssh_keygen
  

- name: Installation des servers (users)
  hosts: webserver
  become: yes
  roles:
  - create_users

  