- name: how to use ssh module
  hosts: all
  
  tasks:
  - name: generation de la clef
    openssh_keypair:
      path: /tmp/franky
      type: rsa
      size: 4096
      state: present
      force: no
    delegate_to: localhost
    run_once: yes
  - name: creation du user devops
    user:
      name: devops
      shell: /bin/bash
      group: sudo
      append: yes
      password: "{{ 'password' | password_hash('sha512') }}"
    become: yes

  - name: Add devops user to the sudoers
    copy:
      dest: "/etc/sudoers.d/devops"
      content: "devops ALL=(ALL) NOPASSWD: ALL"
    become: yes

  - name: Deploy SSH Key
    authorized_key:
      user: devops
      key: "{{ lookup('file', '/tmp/franky.pub') }}"
      state: present
    become: yes


    