- name: how to use reboot module
  hosts: nocommon
  become: yes
  tasks:
  - name: creation du fichier franky.txt
    file:
      state: touch
      path: /tmp/franky.txt
 
  - name: test la presence du franky.txt
    stat:
      path: /tmp/franky.txt
    register: __fichier_franky

  - name: reboot de la machine
    reboot:
      msg: "Reboot via ansible"
      connect_timeout: 5
      pre_reboot_delay: 0
      post_reboot_delay: 10
      test_command: uptime
    when: __fichier_franky.stat.exists
  
  - name: creation d'un deuxieme fichier
    file:
      path: /tmp/reboot_ok.txt
      state: touch
      

  