- name: playbook stat & register
  hosts: all
  become: yes
  tasks:
  #- name: creation du fichier francky.txt
  #  file:
  #  path: /tmp/francky.txt
  #  state: touch
  #  owner: mint212
  #  group: mint212
  - name: test de stat
    stat:
      path: /tmp/francky.txt
    register: __st_francky
  - name: affichage de register
    debug:
      msg: "Mon fichier : {{ __st_francky.stat.exists }}"
  - name : creation du repertoire si le fichier existe
    file:
      path: /tmp/chocky
      state: directory
    when: __st_francky.stat.exists == true