- name: utilisatin de lineinfile
  hosts: all
  become: yes
  tasks:

  - name: lineinfile
    lineinfile: 
      dest: /tmp/test.conf 
      line: "test2"
      state: present
      create: True

  - name: lineinfile test 2
    lineinfile:
      dest: /tmp/test.conf
      line: "test 2"
      regexp: "^test$"
      state: present
      create: True

  - name: lineinfile test capture
    lineinfile:
      dest: /tmp/test.conf
      line: 'je suis le nombre : \1'
      regexp: "^test ([0-2])$"
      backrefs: yes
      state: present
      create: True

  - name: lineinfile test comment
    lineinfile:
      dest: /tmp/test.conf
      line: '# \1'
      regexp: "(^je suis le nombre : [0-2])"
      backrefs: yes
      state: present
      create: True

  - name: lineinfile test insertbefore
    lineinfile:
      dest: /tmp/test.conf
      line: "Ma nouvelle ligne"
      insertbefore: '# je suis le nombre : [0-2]'
      state: present
      create: True

  - name: lineinfile test delete line
    lineinfile:
      dest: /tmp/test.conf
      regexp: "^Ma nouvelle ligne"
      #line: "^Ma nouvelle ligne"
      state: absent

  - name: lineinfile test backup
    lineinfile: 
      dest: /tmp/test.conf
      regexp: "^#"
      state: absent
      backup: yes




  





